name: send mail on push
on:
  push:
    branches:
      - main
jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: 'Your repository name: ${{ github.Harjutus_10 }}'
          body: 'Message: ${{ github.event.head_commit.message }}'
          from: vlademirguzov@gmail.com
          to: infoman724@gmail.com
          

