    on: [push]
    jobs:
      mail_on_push:
        runs-on: ubuntu-latest
        steps:
          - name: Send mail
            uses: dawidd6/action-send-mail@v3
            with:
              server_address: smtp.gmail.com
              server_port: 465
              username: ${{ secrets.MAIL_USERNAME }}
              password: ${{ secrets.MAIL_PASSWORD }}
              subject: 'Your repository name: ${{ github.repository }}'
              body: 'Message: ${{ github.event.head_commit.message }}'
              from: Github actions
              to: infoman724@gmail.com
          

